/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'christoffer' at '7/12/16 8:56 PM' with Gradle 2.13
 *
 * @author christoffer, @date 7/12/16 8:56 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
